//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Library.Repository.Mssql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class timesheetsEntities : DbContext
    {
        public timesheetsEntities()
            : base("name=timesheetsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<SecurityToken> SecurityToken { get; set; }
        public virtual DbSet<ClientConsultant> ClientConsultant { get; set; }
        public virtual DbSet<Timesheet> Timesheet { get; set; }
        public virtual DbSet<TimesheetDay> TimesheetDay { get; set; }
        public virtual DbSet<VendorConsultant> VendorConsultant { get; set; }
        public virtual DbSet<VendorClient> VendorClient { get; set; }
        public virtual DbSet<vwClientConsultant> vwClientConsultant { get; set; }
        public virtual DbSet<vwClientByConsultant> vwClientByConsultant { get; set; }
        public virtual DbSet<vwVendorConsultant> vwVendorConsultant { get; set; }
        public virtual DbSet<vwVendorClient> vwVendorClient { get; set; }
        public virtual DbSet<vwTimesheetClient> vwTimesheetClient { get; set; }
        public virtual DbSet<vwTimesheetConsultant> vwTimesheetConsultant { get; set; }
        public virtual DbSet<vwTimesheetVendor> vwTimesheetVendor { get; set; }
    }
}
