//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Library.Repository.Mssql
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SecurityToken = new HashSet<SecurityToken>();
            this.ClientConsultant = new HashSet<ClientConsultant>();
            this.ClientConsultant1 = new HashSet<ClientConsultant>();
            this.VendorConsultant = new HashSet<VendorConsultant>();
            this.VendorConsultant1 = new HashSet<VendorConsultant>();
            this.VendorClient = new HashSet<VendorClient>();
            this.VendorClient1 = new HashSet<VendorClient>();
        }
    
        public int id { get; set; }
        public System.DateTime CreatedDTS { get; set; }
        public System.DateTime UpdatedDTS { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Type { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Url { get; set; }
        public string TaxCode { get; set; }
        public string Logo { get; set; }
        public string Contact { get; set; }
    
        public virtual ICollection<SecurityToken> SecurityToken { get; set; }
        public virtual ICollection<ClientConsultant> ClientConsultant { get; set; }
        public virtual ICollection<ClientConsultant> ClientConsultant1 { get; set; }
        public virtual ICollection<VendorConsultant> VendorConsultant { get; set; }
        public virtual ICollection<VendorConsultant> VendorConsultant1 { get; set; }
        public virtual ICollection<VendorClient> VendorClient { get; set; }
        public virtual ICollection<VendorClient> VendorClient1 { get; set; }
    }
}
