//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Library.Repository.Mssql
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorClient
    {
        public VendorClient()
        {
            this.ClientConsultant = new HashSet<ClientConsultant>();
        }
    
        public int id { get; set; }
        public int VendorId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime CreatedDTS { get; set; }
        public System.DateTime UpdatedDTS { get; set; }
    
        public virtual ICollection<ClientConsultant> ClientConsultant { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
