//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Library.Repository.Mssql
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVendorConsultant
    {
        public int VendorConsultantId { get; set; }
        public int VendorId { get; set; }
        public int ConsultantId { get; set; }
        public System.DateTime VendorConsultantCreatedDTS { get; set; }
        public System.DateTime VendorConsultantUpdatedDTS { get; set; }
        public int id { get; set; }
        public System.DateTime CreatedDTS { get; set; }
        public System.DateTime UpdatedDTS { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Type { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Url { get; set; }
        public string TaxCode { get; set; }
        public string Logo { get; set; }
        public string Contact { get; set; }
    }
}
