app.config(['$routeProvider',
  function ($routeProvider) {
      $routeProvider.
        when('/', {
            controller: 'homeController',
            templateUrl: 'views/home.html'
        }).when('/remind', {
            controller: 'userController',
            templateUrl: 'views/remind.html'
        }).when('/register', {
            controller: 'userController',
            templateUrl: 'views/register.html'
        }).when('/login', {
            controller: 'userController',
            templateUrl: 'views/login.html'
        }).when('/logout', {
            controller: 'userController',
            templateUrl: 'views/logout.html'
        }).when('/clients', {
            controller: 'clientController',
            templateUrl: 'views/clients.html'
        }).when('/addclient', {
            controller: 'clientController',
            templateUrl: 'views/addclient.html'
        }).when('/client/:id', {
            controller: 'clientController',
            templateUrl: 'views/client.html'
        }).when('/confirmdeleteclient/:id', {
            controller: 'clientController',
            templateUrl: 'views/confirmdeleteclient.html'
        }).when('/consultants', {
            controller: 'consultantController',
            templateUrl: 'views/consultants.html'
        }).when('/addconsultant', {
            controller: 'consultantController',
            templateUrl: 'views/addconsultant.html'
        }).when('/consultant/:id', {
            controller: 'consultantController',
            templateUrl: 'views/consultant.html'
        }).when('/confirmdeleteconsultant/:id', {
            controller: 'consultantController',
            templateUrl: 'views/confirmdeleteconsultant.html'
        }).when('/contracts', {
            controller: 'contractController',
            templateUrl: 'views/contracts.html'
        }).when('/addcontract', {
            controller: 'contractController',
            templateUrl: 'views/addcontract.html'
        }).when('/confirmdeletecontract/:id', {
            controller: 'contractController',
            templateUrl: 'views/confirmdeletecontract.html'
        }).when('/timesheets', {
            controller: 'timesheetController',
            templateUrl: 'views/timesheets.html'
        }).when('/addtimesheet', {
            controller: 'timesheetController',
            templateUrl: 'views/timesheet.html'
        }).when('/timesheet/:id', {
            controller: 'timesheetController',
            templateUrl: 'views/timesheet.html'
        }).when('/confirmdeletetimesheet/:id', {
            controller: 'timesheetController',
            templateUrl: 'views/confirmdeletetimesheet.html'
        }).when('/account', {
            controller: 'userController',
            templateUrl: 'views/account.html'
        }).when('/password', {
            controller: 'userController',
            templateUrl: 'views/password.html'
        });
  }]);